# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('lives', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('followers', models.IntegerField(default=0, null=True)),
                ('following', models.IntegerField(default=0, null=True)),
                ('work', models.CharField(max_length=200, null=True)),
                ('studied', models.CharField(max_length=200, null=True)),
                ('profession', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(max_length=200, null=True)),
                ('motto', models.CharField(max_length=200, null=True)),
                ('about_me', models.TextField(max_length=500, null=True)),
                ('edit_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
